[package]
name = "a-bot"
version = "0.1.0"
authors = ["wozeparrot"]
edition = "2018"
license = "AGPL"
description = "Asynchronous FRC Library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
