[package]
name = "rbotlib"
version = "0.0.1"
authors = ["wozeparrot"]
edition = "2018"
license = "BSD-3-Clause"
description = "Rust FRC Library"
repository = "https://github.com/wozeparrot/rbot"

[dependencies]
rbothal = { path = "../rbothal", version = "0.0.1" }